apiVersion: v1
entries:
  oraoperator-app:
  - apiVersion: v2
    appVersion: 19.0.0
    created: "2024-12-16T02:09:57.663723+01:00"
    description: A Helm chart for Oracle Database Operator deployment with test application
      and supporting components for Oracle 19c database management
    digest: a1d0e324152c9e6ae81714ec4b51b930c643dfc516ea0738444838b432e106ea
    keywords:
    - oracle
    - database
    - operator
    - oracle19c
    - cdb
    - pdb
    name: oraoperator-app
    type: application
    urls:
    - oraoperator-app-0.1.0.tgz
    version: 0.1.0
generated: "2024-12-16T02:09:57.662608+01:00"
